export const HOME_PAGE_LOADED_START = "HOME_PAGE_LOADED_START";
export const HOME_PAGE_LOADED_END = "HOME_PAGE_LOADED_END";
export const SET_PAGE_START = "SET_PAGE_START";
export const SET_PAGE_END = "SET_PAGE_END";
export const APPLY_TAG_FILTER_START = "APPLY_TAG_FILTER_START";
export const APPLY_TAG_FILTER_END = "APPLY_TAG_FILTER_END";
export const UPDATE_TAG = "UPDATE_TAG";
export const SET_LOADING = "SET_LOADING";
